services:
  postgres:
    image: 'postgres:15.2'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: finance
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"
  
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
      

volumes:
  pgdata:
    driver: local